package com.example.starrail.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table char_build_sug
 */
public class CharBuildSug {
    /**
     * Database Column Remarks:
     *   角色配装建议id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_build_sug.char_build_sug_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Integer charBuildSugId;

    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_build_sug.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Integer characterId;

    /**
     * Database Column Remarks:
     *   配装建议
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_build_sug.build_sug
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private String buildSug;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_build_sug.char_build_sug_id
     *
     * @return the value of char_build_sug.char_build_sug_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Integer getCharBuildSugId() {
        return charBuildSugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_build_sug.char_build_sug_id
     *
     * @param charBuildSugId the value for char_build_sug.char_build_sug_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setCharBuildSugId(Integer charBuildSugId) {
        this.charBuildSugId = charBuildSugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_build_sug.character_id
     *
     * @return the value of char_build_sug.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_build_sug.character_id
     *
     * @param characterId the value for char_build_sug.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_build_sug.build_sug
     *
     * @return the value of char_build_sug.build_sug
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public String getBuildSug() {
        return buildSug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_build_sug.build_sug
     *
     * @param buildSug the value for char_build_sug.build_sug
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setBuildSug(String buildSug) {
        this.buildSug = buildSug == null ? null : buildSug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CharBuildSug other = (CharBuildSug) that;
        return (this.getCharBuildSugId() == null ? other.getCharBuildSugId() == null : this.getCharBuildSugId().equals(other.getCharBuildSugId()))
            && (this.getCharacterId() == null ? other.getCharacterId() == null : this.getCharacterId().equals(other.getCharacterId()))
            && (this.getBuildSug() == null ? other.getBuildSug() == null : this.getBuildSug().equals(other.getBuildSug()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCharBuildSugId() == null) ? 0 : getCharBuildSugId().hashCode());
        result = prime * result + ((getCharacterId() == null) ? 0 : getCharacterId().hashCode());
        result = prime * result + ((getBuildSug() == null) ? 0 : getBuildSug().hashCode());
        return result;
    }
}