package com.example.starrail.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table char_options
 */
public class CharOptions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_options.char_option_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Integer charOptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_options.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Integer characterId;

    /**
     * Database Column Remarks:
     *   是否支持散件，0 否，1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column char_options.can_rainbow_build
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Boolean canRainbowBuild;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_options.char_option_id
     *
     * @return the value of char_options.char_option_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Integer getCharOptionId() {
        return charOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_options.char_option_id
     *
     * @param charOptionId the value for char_options.char_option_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setCharOptionId(Integer charOptionId) {
        this.charOptionId = charOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_options.character_id
     *
     * @return the value of char_options.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_options.character_id
     *
     * @param characterId the value for char_options.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column char_options.can_rainbow_build
     *
     * @return the value of char_options.can_rainbow_build
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Boolean getCanRainbowBuild() {
        return canRainbowBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column char_options.can_rainbow_build
     *
     * @param canRainbowBuild the value for char_options.can_rainbow_build
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setCanRainbowBuild(Boolean canRainbowBuild) {
        this.canRainbowBuild = canRainbowBuild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CharOptions other = (CharOptions) that;
        return (this.getCharOptionId() == null ? other.getCharOptionId() == null : this.getCharOptionId().equals(other.getCharOptionId()))
            && (this.getCharacterId() == null ? other.getCharacterId() == null : this.getCharacterId().equals(other.getCharacterId()))
            && (this.getCanRainbowBuild() == null ? other.getCanRainbowBuild() == null : this.getCanRainbowBuild().equals(other.getCanRainbowBuild()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCharOptionId() == null) ? 0 : getCharOptionId().hashCode());
        result = prime * result + ((getCharacterId() == null) ? 0 : getCharacterId().hashCode());
        result = prime * result + ((getCanRainbowBuild() == null) ? 0 : getCanRainbowBuild().hashCode());
        return result;
    }
}