package com.example.starrail.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table relic_entity
 */
public class RelicEntity {
    /**
     * Database Column Remarks:
     *   遗器id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_entity.relic_entity_id
     *
     * @mbg.generated
     */
    private Integer relicEntityId;

    /**
     * Database Column Remarks:
     *   遗器等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_entity.relic_level
     *
     * @mbg.generated
     */
    private Integer relicLevel;

    /**
     * Database Column Remarks:
     *   遗器套装id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_entity.relic_set_id
     *
     * @mbg.generated
     */
    private Integer relicSetId;

    /**
     * Database Column Remarks:
     *   遗器部位id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_entity.relic_type_id
     *
     * @mbg.generated
     */
    private Integer relicTypeId;

    /**
     * Database Column Remarks:
     *   主词条id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_entity.main_stat_id
     *
     * @mbg.generated
     */
    private Integer mainStatId;

    /**
     * Database Column Remarks:
     *   副词条及值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_entity.sub_stat_values
     *
     * @mbg.generated
     */
    private String subStatValues;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_entity.relic_entity_id
     *
     * @return the value of relic_entity.relic_entity_id
     *
     * @mbg.generated
     */
    public Integer getRelicEntityId() {
        return relicEntityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_entity.relic_entity_id
     *
     * @param relicEntityId the value for relic_entity.relic_entity_id
     *
     * @mbg.generated
     */
    public void setRelicEntityId(Integer relicEntityId) {
        this.relicEntityId = relicEntityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_entity.relic_level
     *
     * @return the value of relic_entity.relic_level
     *
     * @mbg.generated
     */
    public Integer getRelicLevel() {
        return relicLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_entity.relic_level
     *
     * @param relicLevel the value for relic_entity.relic_level
     *
     * @mbg.generated
     */
    public void setRelicLevel(Integer relicLevel) {
        this.relicLevel = relicLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_entity.relic_set_id
     *
     * @return the value of relic_entity.relic_set_id
     *
     * @mbg.generated
     */
    public Integer getRelicSetId() {
        return relicSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_entity.relic_set_id
     *
     * @param relicSetId the value for relic_entity.relic_set_id
     *
     * @mbg.generated
     */
    public void setRelicSetId(Integer relicSetId) {
        this.relicSetId = relicSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_entity.relic_type_id
     *
     * @return the value of relic_entity.relic_type_id
     *
     * @mbg.generated
     */
    public Integer getRelicTypeId() {
        return relicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_entity.relic_type_id
     *
     * @param relicTypeId the value for relic_entity.relic_type_id
     *
     * @mbg.generated
     */
    public void setRelicTypeId(Integer relicTypeId) {
        this.relicTypeId = relicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_entity.main_stat_id
     *
     * @return the value of relic_entity.main_stat_id
     *
     * @mbg.generated
     */
    public Integer getMainStatId() {
        return mainStatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_entity.main_stat_id
     *
     * @param mainStatId the value for relic_entity.main_stat_id
     *
     * @mbg.generated
     */
    public void setMainStatId(Integer mainStatId) {
        this.mainStatId = mainStatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_entity.sub_stat_values
     *
     * @return the value of relic_entity.sub_stat_values
     *
     * @mbg.generated
     */
    public String getSubStatValues() {
        return subStatValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_entity.sub_stat_values
     *
     * @param subStatValues the value for relic_entity.sub_stat_values
     *
     * @mbg.generated
     */
    public void setSubStatValues(String subStatValues) {
        this.subStatValues = subStatValues == null ? null : subStatValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RelicEntity other = (RelicEntity) that;
        return (this.getRelicEntityId() == null ? other.getRelicEntityId() == null : this.getRelicEntityId().equals(other.getRelicEntityId()))
            && (this.getRelicLevel() == null ? other.getRelicLevel() == null : this.getRelicLevel().equals(other.getRelicLevel()))
            && (this.getRelicSetId() == null ? other.getRelicSetId() == null : this.getRelicSetId().equals(other.getRelicSetId()))
            && (this.getRelicTypeId() == null ? other.getRelicTypeId() == null : this.getRelicTypeId().equals(other.getRelicTypeId()))
            && (this.getMainStatId() == null ? other.getMainStatId() == null : this.getMainStatId().equals(other.getMainStatId()))
            && (this.getSubStatValues() == null ? other.getSubStatValues() == null : this.getSubStatValues().equals(other.getSubStatValues()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRelicEntityId() == null) ? 0 : getRelicEntityId().hashCode());
        result = prime * result + ((getRelicLevel() == null) ? 0 : getRelicLevel().hashCode());
        result = prime * result + ((getRelicSetId() == null) ? 0 : getRelicSetId().hashCode());
        result = prime * result + ((getRelicTypeId() == null) ? 0 : getRelicTypeId().hashCode());
        result = prime * result + ((getMainStatId() == null) ? 0 : getMainStatId().hashCode());
        result = prime * result + ((getSubStatValues() == null) ? 0 : getSubStatValues().hashCode());
        return result;
    }
}