package com.example.starrail.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table relic_type
 */
public class RelicType {
    /**
     * Database Column Remarks:
     *   遗器部位id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.relic_type_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Integer relicTypeId;

    /**
     * Database Column Remarks:
     *   遗器部位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.relic_type_name
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private String relicTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.relic_type_id
     *
     * @return the value of relic_type.relic_type_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Integer getRelicTypeId() {
        return relicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.relic_type_id
     *
     * @param relicTypeId the value for relic_type.relic_type_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setRelicTypeId(Integer relicTypeId) {
        this.relicTypeId = relicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.relic_type_name
     *
     * @return the value of relic_type.relic_type_name
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public String getRelicTypeName() {
        return relicTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.relic_type_name
     *
     * @param relicTypeName the value for relic_type.relic_type_name
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setRelicTypeName(String relicTypeName) {
        this.relicTypeName = relicTypeName == null ? null : relicTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RelicType other = (RelicType) that;
        return (this.getRelicTypeId() == null ? other.getRelicTypeId() == null : this.getRelicTypeId().equals(other.getRelicTypeId()))
            && (this.getRelicTypeName() == null ? other.getRelicTypeName() == null : this.getRelicTypeName().equals(other.getRelicTypeName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRelicTypeId() == null) ? 0 : getRelicTypeId().hashCode());
        result = prime * result + ((getRelicTypeName() == null) ? 0 : getRelicTypeName().hashCode());
        return result;
    }
}