package com.example.starrail.po;

import java.util.ArrayList;
import java.util.List;

public class RelicFitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public RelicFitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelicFitIdIsNull() {
            addCriterion("relic_fit_id is null");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdIsNotNull() {
            addCriterion("relic_fit_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdEqualTo(Integer value) {
            addCriterion("relic_fit_id =", value, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdNotEqualTo(Integer value) {
            addCriterion("relic_fit_id <>", value, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdGreaterThan(Integer value) {
            addCriterion("relic_fit_id >", value, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_fit_id >=", value, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdLessThan(Integer value) {
            addCriterion("relic_fit_id <", value, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdLessThanOrEqualTo(Integer value) {
            addCriterion("relic_fit_id <=", value, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdIn(List<Integer> values) {
            addCriterion("relic_fit_id in", values, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdNotIn(List<Integer> values) {
            addCriterion("relic_fit_id not in", values, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdBetween(Integer value1, Integer value2) {
            addCriterion("relic_fit_id between", value1, value2, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicFitIdNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_fit_id not between", value1, value2, "relicFitId");
            return (Criteria) this;
        }

        public Criteria andRelicIdIsNull() {
            addCriterion("relic_id is null");
            return (Criteria) this;
        }

        public Criteria andRelicIdIsNotNull() {
            addCriterion("relic_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelicIdEqualTo(Integer value) {
            addCriterion("relic_id =", value, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdNotEqualTo(Integer value) {
            addCriterion("relic_id <>", value, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdGreaterThan(Integer value) {
            addCriterion("relic_id >", value, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_id >=", value, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdLessThan(Integer value) {
            addCriterion("relic_id <", value, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdLessThanOrEqualTo(Integer value) {
            addCriterion("relic_id <=", value, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdIn(List<Integer> values) {
            addCriterion("relic_id in", values, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdNotIn(List<Integer> values) {
            addCriterion("relic_id not in", values, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdBetween(Integer value1, Integer value2) {
            addCriterion("relic_id between", value1, value2, "relicId");
            return (Criteria) this;
        }

        public Criteria andRelicIdNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_id not between", value1, value2, "relicId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdIsNull() {
            addCriterion("character_id is null");
            return (Criteria) this;
        }

        public Criteria andCharacterIdIsNotNull() {
            addCriterion("character_id is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterIdEqualTo(Integer value) {
            addCriterion("character_id =", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdNotEqualTo(Integer value) {
            addCriterion("character_id <>", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdGreaterThan(Integer value) {
            addCriterion("character_id >", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("character_id >=", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdLessThan(Integer value) {
            addCriterion("character_id <", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdLessThanOrEqualTo(Integer value) {
            addCriterion("character_id <=", value, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdIn(List<Integer> values) {
            addCriterion("character_id in", values, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdNotIn(List<Integer> values) {
            addCriterion("character_id not in", values, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdBetween(Integer value1, Integer value2) {
            addCriterion("character_id between", value1, value2, "characterId");
            return (Criteria) this;
        }

        public Criteria andCharacterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("character_id not between", value1, value2, "characterId");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitIsNull() {
            addCriterion("is_main_stat_fit is null");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitIsNotNull() {
            addCriterion("is_main_stat_fit is not null");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitEqualTo(Boolean value) {
            addCriterion("is_main_stat_fit =", value, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitNotEqualTo(Boolean value) {
            addCriterion("is_main_stat_fit <>", value, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitGreaterThan(Boolean value) {
            addCriterion("is_main_stat_fit >", value, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_main_stat_fit >=", value, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitLessThan(Boolean value) {
            addCriterion("is_main_stat_fit <", value, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitLessThanOrEqualTo(Boolean value) {
            addCriterion("is_main_stat_fit <=", value, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitIn(List<Boolean> values) {
            addCriterion("is_main_stat_fit in", values, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitNotIn(List<Boolean> values) {
            addCriterion("is_main_stat_fit not in", values, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitBetween(Boolean value1, Boolean value2) {
            addCriterion("is_main_stat_fit between", value1, value2, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsMainStatFitNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_main_stat_fit not between", value1, value2, "isMainStatFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitIsNull() {
            addCriterion("is_relic_set_fit is null");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitIsNotNull() {
            addCriterion("is_relic_set_fit is not null");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitEqualTo(Boolean value) {
            addCriterion("is_relic_set_fit =", value, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitNotEqualTo(Boolean value) {
            addCriterion("is_relic_set_fit <>", value, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitGreaterThan(Boolean value) {
            addCriterion("is_relic_set_fit >", value, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_relic_set_fit >=", value, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitLessThan(Boolean value) {
            addCriterion("is_relic_set_fit <", value, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitLessThanOrEqualTo(Boolean value) {
            addCriterion("is_relic_set_fit <=", value, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitIn(List<Boolean> values) {
            addCriterion("is_relic_set_fit in", values, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitNotIn(List<Boolean> values) {
            addCriterion("is_relic_set_fit not in", values, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitBetween(Boolean value1, Boolean value2) {
            addCriterion("is_relic_set_fit between", value1, value2, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andIsRelicSetFitNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_relic_set_fit not between", value1, value2, "isRelicSetFit");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessIsNull() {
            addCriterion("sub_stat_fitness is null");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessIsNotNull() {
            addCriterion("sub_stat_fitness is not null");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessEqualTo(Double value) {
            addCriterion("sub_stat_fitness =", value, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessNotEqualTo(Double value) {
            addCriterion("sub_stat_fitness <>", value, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessGreaterThan(Double value) {
            addCriterion("sub_stat_fitness >", value, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessGreaterThanOrEqualTo(Double value) {
            addCriterion("sub_stat_fitness >=", value, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessLessThan(Double value) {
            addCriterion("sub_stat_fitness <", value, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessLessThanOrEqualTo(Double value) {
            addCriterion("sub_stat_fitness <=", value, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessIn(List<Double> values) {
            addCriterion("sub_stat_fitness in", values, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessNotIn(List<Double> values) {
            addCriterion("sub_stat_fitness not in", values, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessBetween(Double value1, Double value2) {
            addCriterion("sub_stat_fitness between", value1, value2, "subStatFitness");
            return (Criteria) this;
        }

        public Criteria andSubStatFitnessNotBetween(Double value1, Double value2) {
            addCriterion("sub_stat_fitness not between", value1, value2, "subStatFitness");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_fit
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}