package com.example.starrail.po;

import java.util.ArrayList;
import java.util.List;

public class RelicEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public RelicEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelicEntityIdIsNull() {
            addCriterion("relic_entity_id is null");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdIsNotNull() {
            addCriterion("relic_entity_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdEqualTo(Integer value) {
            addCriterion("relic_entity_id =", value, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdNotEqualTo(Integer value) {
            addCriterion("relic_entity_id <>", value, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdGreaterThan(Integer value) {
            addCriterion("relic_entity_id >", value, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_entity_id >=", value, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdLessThan(Integer value) {
            addCriterion("relic_entity_id <", value, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdLessThanOrEqualTo(Integer value) {
            addCriterion("relic_entity_id <=", value, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdIn(List<Integer> values) {
            addCriterion("relic_entity_id in", values, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdNotIn(List<Integer> values) {
            addCriterion("relic_entity_id not in", values, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdBetween(Integer value1, Integer value2) {
            addCriterion("relic_entity_id between", value1, value2, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicEntityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_entity_id not between", value1, value2, "relicEntityId");
            return (Criteria) this;
        }

        public Criteria andRelicLevelIsNull() {
            addCriterion("relic_level is null");
            return (Criteria) this;
        }

        public Criteria andRelicLevelIsNotNull() {
            addCriterion("relic_level is not null");
            return (Criteria) this;
        }

        public Criteria andRelicLevelEqualTo(Integer value) {
            addCriterion("relic_level =", value, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelNotEqualTo(Integer value) {
            addCriterion("relic_level <>", value, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelGreaterThan(Integer value) {
            addCriterion("relic_level >", value, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_level >=", value, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelLessThan(Integer value) {
            addCriterion("relic_level <", value, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelLessThanOrEqualTo(Integer value) {
            addCriterion("relic_level <=", value, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelIn(List<Integer> values) {
            addCriterion("relic_level in", values, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelNotIn(List<Integer> values) {
            addCriterion("relic_level not in", values, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelBetween(Integer value1, Integer value2) {
            addCriterion("relic_level between", value1, value2, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_level not between", value1, value2, "relicLevel");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdIsNull() {
            addCriterion("relic_set_id is null");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdIsNotNull() {
            addCriterion("relic_set_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdEqualTo(Integer value) {
            addCriterion("relic_set_id =", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdNotEqualTo(Integer value) {
            addCriterion("relic_set_id <>", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdGreaterThan(Integer value) {
            addCriterion("relic_set_id >", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_set_id >=", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdLessThan(Integer value) {
            addCriterion("relic_set_id <", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdLessThanOrEqualTo(Integer value) {
            addCriterion("relic_set_id <=", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdIn(List<Integer> values) {
            addCriterion("relic_set_id in", values, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdNotIn(List<Integer> values) {
            addCriterion("relic_set_id not in", values, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdBetween(Integer value1, Integer value2) {
            addCriterion("relic_set_id between", value1, value2, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_set_id not between", value1, value2, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdIsNull() {
            addCriterion("relic_type_id is null");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdIsNotNull() {
            addCriterion("relic_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdEqualTo(Integer value) {
            addCriterion("relic_type_id =", value, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdNotEqualTo(Integer value) {
            addCriterion("relic_type_id <>", value, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdGreaterThan(Integer value) {
            addCriterion("relic_type_id >", value, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_type_id >=", value, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdLessThan(Integer value) {
            addCriterion("relic_type_id <", value, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("relic_type_id <=", value, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdIn(List<Integer> values) {
            addCriterion("relic_type_id in", values, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdNotIn(List<Integer> values) {
            addCriterion("relic_type_id not in", values, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("relic_type_id between", value1, value2, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andRelicTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_type_id not between", value1, value2, "relicTypeId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdIsNull() {
            addCriterion("main_stat_id is null");
            return (Criteria) this;
        }

        public Criteria andMainStatIdIsNotNull() {
            addCriterion("main_stat_id is not null");
            return (Criteria) this;
        }

        public Criteria andMainStatIdEqualTo(Integer value) {
            addCriterion("main_stat_id =", value, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdNotEqualTo(Integer value) {
            addCriterion("main_stat_id <>", value, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdGreaterThan(Integer value) {
            addCriterion("main_stat_id >", value, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("main_stat_id >=", value, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdLessThan(Integer value) {
            addCriterion("main_stat_id <", value, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdLessThanOrEqualTo(Integer value) {
            addCriterion("main_stat_id <=", value, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdIn(List<Integer> values) {
            addCriterion("main_stat_id in", values, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdNotIn(List<Integer> values) {
            addCriterion("main_stat_id not in", values, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdBetween(Integer value1, Integer value2) {
            addCriterion("main_stat_id between", value1, value2, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andMainStatIdNotBetween(Integer value1, Integer value2) {
            addCriterion("main_stat_id not between", value1, value2, "mainStatId");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesIsNull() {
            addCriterion("sub_stat_values is null");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesIsNotNull() {
            addCriterion("sub_stat_values is not null");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesEqualTo(String value) {
            addCriterion("sub_stat_values =", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesNotEqualTo(String value) {
            addCriterion("sub_stat_values <>", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesGreaterThan(String value) {
            addCriterion("sub_stat_values >", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesGreaterThanOrEqualTo(String value) {
            addCriterion("sub_stat_values >=", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesLessThan(String value) {
            addCriterion("sub_stat_values <", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesLessThanOrEqualTo(String value) {
            addCriterion("sub_stat_values <=", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesLike(String value) {
            addCriterion("sub_stat_values like", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesNotLike(String value) {
            addCriterion("sub_stat_values not like", value, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesIn(List<String> values) {
            addCriterion("sub_stat_values in", values, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesNotIn(List<String> values) {
            addCriterion("sub_stat_values not in", values, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesBetween(String value1, String value2) {
            addCriterion("sub_stat_values between", value1, value2, "subStatValues");
            return (Criteria) this;
        }

        public Criteria andSubStatValuesNotBetween(String value1, String value2) {
            addCriterion("sub_stat_values not between", value1, value2, "subStatValues");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_entity
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}