package com.example.starrail.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table relic_set
 */
public class RelicSet {
    /**
     * Database Column Remarks:
     *   遗器套装id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_set.relic_set_id
     *
     * @mbg.generated
     */
    private Integer relicSetId;

    /**
     * Database Column Remarks:
     *   遗器套装类型，外圈还是内圈，外圈1，内圈2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_set.relic_set_type
     *
     * @mbg.generated
     */
    private Integer relicSetType;

    /**
     * Database Column Remarks:
     *   遗器套装名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_set.relic_set_name
     *
     * @mbg.generated
     */
    private String relicSetName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_set.relic_set_id
     *
     * @return the value of relic_set.relic_set_id
     *
     * @mbg.generated
     */
    public Integer getRelicSetId() {
        return relicSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_set.relic_set_id
     *
     * @param relicSetId the value for relic_set.relic_set_id
     *
     * @mbg.generated
     */
    public void setRelicSetId(Integer relicSetId) {
        this.relicSetId = relicSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_set.relic_set_type
     *
     * @return the value of relic_set.relic_set_type
     *
     * @mbg.generated
     */
    public Integer getRelicSetType() {
        return relicSetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_set.relic_set_type
     *
     * @param relicSetType the value for relic_set.relic_set_type
     *
     * @mbg.generated
     */
    public void setRelicSetType(Integer relicSetType) {
        this.relicSetType = relicSetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_set.relic_set_name
     *
     * @return the value of relic_set.relic_set_name
     *
     * @mbg.generated
     */
    public String getRelicSetName() {
        return relicSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_set.relic_set_name
     *
     * @param relicSetName the value for relic_set.relic_set_name
     *
     * @mbg.generated
     */
    public void setRelicSetName(String relicSetName) {
        this.relicSetName = relicSetName == null ? null : relicSetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RelicSet other = (RelicSet) that;
        return (this.getRelicSetId() == null ? other.getRelicSetId() == null : this.getRelicSetId().equals(other.getRelicSetId()))
            && (this.getRelicSetType() == null ? other.getRelicSetType() == null : this.getRelicSetType().equals(other.getRelicSetType()))
            && (this.getRelicSetName() == null ? other.getRelicSetName() == null : this.getRelicSetName().equals(other.getRelicSetName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRelicSetId() == null) ? 0 : getRelicSetId().hashCode());
        result = prime * result + ((getRelicSetType() == null) ? 0 : getRelicSetType().hashCode());
        result = prime * result + ((getRelicSetName() == null) ? 0 : getRelicSetName().hashCode());
        return result;
    }
}