package com.example.starrail.po;

import java.util.ArrayList;
import java.util.List;

public class RelicSetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public RelicSetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelicSetIdIsNull() {
            addCriterion("relic_set_id is null");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdIsNotNull() {
            addCriterion("relic_set_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdEqualTo(Integer value) {
            addCriterion("relic_set_id =", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdNotEqualTo(Integer value) {
            addCriterion("relic_set_id <>", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdGreaterThan(Integer value) {
            addCriterion("relic_set_id >", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_set_id >=", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdLessThan(Integer value) {
            addCriterion("relic_set_id <", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdLessThanOrEqualTo(Integer value) {
            addCriterion("relic_set_id <=", value, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdIn(List<Integer> values) {
            addCriterion("relic_set_id in", values, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdNotIn(List<Integer> values) {
            addCriterion("relic_set_id not in", values, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdBetween(Integer value1, Integer value2) {
            addCriterion("relic_set_id between", value1, value2, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_set_id not between", value1, value2, "relicSetId");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeIsNull() {
            addCriterion("relic_set_type is null");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeIsNotNull() {
            addCriterion("relic_set_type is not null");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeEqualTo(Integer value) {
            addCriterion("relic_set_type =", value, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeNotEqualTo(Integer value) {
            addCriterion("relic_set_type <>", value, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeGreaterThan(Integer value) {
            addCriterion("relic_set_type >", value, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("relic_set_type >=", value, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeLessThan(Integer value) {
            addCriterion("relic_set_type <", value, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeLessThanOrEqualTo(Integer value) {
            addCriterion("relic_set_type <=", value, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeIn(List<Integer> values) {
            addCriterion("relic_set_type in", values, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeNotIn(List<Integer> values) {
            addCriterion("relic_set_type not in", values, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeBetween(Integer value1, Integer value2) {
            addCriterion("relic_set_type between", value1, value2, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("relic_set_type not between", value1, value2, "relicSetType");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameIsNull() {
            addCriterion("relic_set_name is null");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameIsNotNull() {
            addCriterion("relic_set_name is not null");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameEqualTo(String value) {
            addCriterion("relic_set_name =", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameNotEqualTo(String value) {
            addCriterion("relic_set_name <>", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameGreaterThan(String value) {
            addCriterion("relic_set_name >", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameGreaterThanOrEqualTo(String value) {
            addCriterion("relic_set_name >=", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameLessThan(String value) {
            addCriterion("relic_set_name <", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameLessThanOrEqualTo(String value) {
            addCriterion("relic_set_name <=", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameLike(String value) {
            addCriterion("relic_set_name like", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameNotLike(String value) {
            addCriterion("relic_set_name not like", value, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameIn(List<String> values) {
            addCriterion("relic_set_name in", values, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameNotIn(List<String> values) {
            addCriterion("relic_set_name not in", values, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameBetween(String value1, String value2) {
            addCriterion("relic_set_name between", value1, value2, "relicSetName");
            return (Criteria) this;
        }

        public Criteria andRelicSetNameNotBetween(String value1, String value2) {
            addCriterion("relic_set_name not between", value1, value2, "relicSetName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_set
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relic_set
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}