package com.example.starrail.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table star_rail_character
 */
public class StarRailCharacter {
    /**
     * Database Column Remarks:
     *   角色 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star_rail_character.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Integer characterId;

    /**
     * Database Column Remarks:
     *   角色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star_rail_character.character_name
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private String characterName;

    /**
     * Database Column Remarks:
     *   是否隐藏, 0 否，1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star_rail_character.is_hide
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    private Boolean isHide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star_rail_character.character_id
     *
     * @return the value of star_rail_character.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star_rail_character.character_id
     *
     * @param characterId the value for star_rail_character.character_id
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star_rail_character.character_name
     *
     * @return the value of star_rail_character.character_name
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public String getCharacterName() {
        return characterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star_rail_character.character_name
     *
     * @param characterName the value for star_rail_character.character_name
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setCharacterName(String characterName) {
        this.characterName = characterName == null ? null : characterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star_rail_character.is_hide
     *
     * @return the value of star_rail_character.is_hide
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public Boolean getIsHide() {
        return isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star_rail_character.is_hide
     *
     * @param isHide the value for star_rail_character.is_hide
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    public void setIsHide(Boolean isHide) {
        this.isHide = isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StarRailCharacter other = (StarRailCharacter) that;
        return (this.getCharacterId() == null ? other.getCharacterId() == null : this.getCharacterId().equals(other.getCharacterId()))
            && (this.getCharacterName() == null ? other.getCharacterName() == null : this.getCharacterName().equals(other.getCharacterName()))
            && (this.getIsHide() == null ? other.getIsHide() == null : this.getIsHide().equals(other.getIsHide()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCharacterId() == null) ? 0 : getCharacterId().hashCode());
        result = prime * result + ((getCharacterName() == null) ? 0 : getCharacterName().hashCode());
        result = prime * result + ((getIsHide() == null) ? 0 : getIsHide().hashCode());
        return result;
    }
}