package com.example.starrail.dao;

import com.example.starrail.po.CharStat;
import com.example.starrail.po.CharStatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    long countByExample(CharStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByExample(CharStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByPrimaryKey(Integer charStatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insert(CharStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insertSelective(CharStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    List<CharStat> selectByExample(CharStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    CharStat selectByPrimaryKey(Integer charStatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExampleSelective(@Param("record") CharStat record, @Param("example") CharStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExample(@Param("record") CharStat record, @Param("example") CharStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKeySelective(CharStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKey(CharStat record);
}