package com.example.starrail.dao;

import com.example.starrail.po.CharBuildSug;
import com.example.starrail.po.CharBuildSugExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharBuildSugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    long countByExample(CharBuildSugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int deleteByExample(CharBuildSugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer charBuildSugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int insert(CharBuildSug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int insertSelective(CharBuildSug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    List<CharBuildSug> selectByExampleWithBLOBs(CharBuildSugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    List<CharBuildSug> selectByExample(CharBuildSugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    CharBuildSug selectByPrimaryKey(Integer charBuildSugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CharBuildSug record, @Param("example") CharBuildSugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CharBuildSug record, @Param("example") CharBuildSugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CharBuildSug record, @Param("example") CharBuildSugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CharBuildSug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CharBuildSug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_build_sug
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CharBuildSug record);
}