package com.example.starrail.dao;

import com.example.starrail.po.CharOptions;
import com.example.starrail.po.CharOptionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    long countByExample(CharOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByExample(CharOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByPrimaryKey(Integer charOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insert(CharOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insertSelective(CharOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    List<CharOptions> selectByExample(CharOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    CharOptions selectByPrimaryKey(Integer charOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExampleSelective(@Param("record") CharOptions record, @Param("example") CharOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExample(@Param("record") CharOptions record, @Param("example") CharOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKeySelective(CharOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_options
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKey(CharOptions record);
}