package com.example.starrail.dao;

import com.example.starrail.po.CharMainStat;
import com.example.starrail.po.CharMainStatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharMainStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    long countByExample(CharMainStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByExample(CharMainStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByPrimaryKey(Integer charMainStatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insert(CharMainStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insertSelective(CharMainStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    List<CharMainStat> selectByExample(CharMainStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    CharMainStat selectByPrimaryKey(Integer charMainStatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExampleSelective(@Param("record") CharMainStat record, @Param("example") CharMainStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExample(@Param("record") CharMainStat record, @Param("example") CharMainStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKeySelective(CharMainStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table char_main_stat
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKey(CharMainStat record);
}