package com.example.starrail.dao;

import com.example.starrail.po.RelicSet;
import com.example.starrail.po.RelicSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelicSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    long countByExample(RelicSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByExample(RelicSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByPrimaryKey(Integer relicSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insert(RelicSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insertSelective(RelicSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    List<RelicSet> selectByExample(RelicSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    RelicSet selectByPrimaryKey(Integer relicSetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExampleSelective(@Param("record") RelicSet record, @Param("example") RelicSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExample(@Param("record") RelicSet record, @Param("example") RelicSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKeySelective(RelicSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_set
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKey(RelicSet record);
}