package com.example.starrail.dao;

import com.example.starrail.po.RelicEntity;
import com.example.starrail.po.RelicEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelicEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    long countByExample(RelicEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int deleteByExample(RelicEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer relicEntityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int insert(RelicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int insertSelective(RelicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    List<RelicEntity> selectByExample(RelicEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    RelicEntity selectByPrimaryKey(Integer relicEntityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RelicEntity record, @Param("example") RelicEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RelicEntity record, @Param("example") RelicEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RelicEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RelicEntity record);
}