package com.example.starrail.dao;

import com.example.starrail.po.RelicType;
import com.example.starrail.po.RelicTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    long countByExample(RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int deleteByExample(RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer relicTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int insert(RelicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int insertSelective(RelicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    List<RelicType> selectByExample(RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    RelicType selectByPrimaryKey(Integer relicTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RelicType record, @Param("example") RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RelicType record, @Param("example") RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RelicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RelicType record);
}