package com.example.starrail.dao;

import com.example.starrail.entity.RelicFitDetail;
import com.example.starrail.entity.RelicFitQuery;
import com.example.starrail.po.RelicFit;
import com.example.starrail.po.RelicFitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelicFitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    long countByExample(RelicFitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int deleteByExample(RelicFitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer relicFitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int insert(RelicFit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int insertSelective(RelicFit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    List<RelicFit> selectByExampleWithBLOBs(RelicFitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    List<RelicFit> selectByExample(RelicFitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    RelicFit selectByPrimaryKey(Integer relicFitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RelicFit record, @Param("example") RelicFitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") RelicFit record, @Param("example") RelicFitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RelicFit record, @Param("example") RelicFitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RelicFit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(RelicFit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_fit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RelicFit record);

    List<RelicFitDetail> getDetailByQuery(@Param("query") RelicFitQuery query);
}