package com.example.starrail.dao;

import com.example.starrail.po.StarRailCharacter;
import com.example.starrail.po.StarRailCharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StarRailCharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    long countByExample(StarRailCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByExample(StarRailCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int deleteByPrimaryKey(Integer characterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insert(StarRailCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int insertSelective(StarRailCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    List<StarRailCharacter> selectByExample(StarRailCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    StarRailCharacter selectByPrimaryKey(Integer characterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExampleSelective(@Param("record") StarRailCharacter record, @Param("example") StarRailCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByExample(@Param("record") StarRailCharacter record, @Param("example") StarRailCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKeySelective(StarRailCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_rail_character
     *
     * @mbg.generated Sat Nov 11 15:15:58 CST 2023
     */
    int updateByPrimaryKey(StarRailCharacter record);
}